# Generated by Django 6.1 on 2026-08-22 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beschreibung', models.CharField(max_length=255)),
                ('betrag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('typ', models.CharField(choices=[('Einnahme', 'Einnahme'), ('Ausgabe', 'Ausgabe')], max_length=10)),
                ('datum', models.DateField()),
                ('kategorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buchungen', to='buchhaltung.kategorie')),
            ],
            options={
                'ordering': ['-datum'],
            },
        ),
    ]
